/**
 * Defaults Module - Index
 * Re-exports all default configurations for clean imports
 */

// Motion defaults
export {
  MOTION_CURVE_STANDARD,
  MOTION_CURVE_PROFESSIONAL,
  MOTION_CURVE_ENTERPRISE,
  SQUASH_STRETCH_DISABLED,
  SQUASH_STRETCH_SUBTLE,
  SQUASH_STRETCH_PROFESSIONAL,
  SQUASH_STRETCH_ENTERPRISE,
  SECONDARY_MOTION_DISABLED,
  SECONDARY_MOTION_SUBTLE,
  SECONDARY_MOTION_PROFESSIONAL,
  SECONDARY_MOTION_ENTERPRISE,
} from './motion';

// Loop defaults
export {
  FREQUENCY_LAYERS_NONE,
  FREQUENCY_LAYERS_SUBTLE,
  FREQUENCY_LAYERS_PROFESSIONAL,
  FREQUENCY_LAYERS_ENTERPRISE,
  NOISE_DISABLED,
  NOISE_SUBTLE,
  NOISE_PROFESSIONAL,
  NOISE_ENTERPRISE,
  MICRO_JITTER_DISABLED,
  MICRO_JITTER_SUBTLE,
  MICRO_JITTER_PROFESSIONAL,
  MICRO_JITTER_ENTERPRISE,
  LOOP_CONFIG_STANDARD,
  LOOP_CONFIG_PROFESSIONAL,
  LOOP_CONFIG_ENTERPRISE,
} from './loop';

// Particle defaults
export {
  PARTICLE_TRAILS_DISABLED,
  PARTICLE_TRAILS_SUBTLE,
  PARTICLE_TRAILS_PROFESSIONAL,
  PARTICLE_TRAILS_ENTERPRISE,
  COLOR_EVOLUTION_DISABLED,
  COLOR_EVOLUTION_FIRE,
  COLOR_EVOLUTION_SPARKLE,
  COLOR_EVOLUTION_RAINBOW,
  SIZE_EVOLUTION_DISABLED,
  SIZE_EVOLUTION_GROW_SHRINK,
  SIZE_EVOLUTION_BURST,
  EMISSION_CONSTANT,
  EMISSION_BURST,
  EMISSION_WAVE,
  PARTICLE_CONFIG_STANDARD,
  PARTICLE_CONFIG_PROFESSIONAL,
  PARTICLE_CONFIG_ENTERPRISE,
} from './particles';

// Global defaults and tier getters
export {
  ANIMATION_CONFIG_STANDARD,
  ANIMATION_CONFIG_PROFESSIONAL,
  ANIMATION_CONFIG_ENTERPRISE,
  ENTRY_CONFIG_STANDARD,
  ENTRY_CONFIG_PROFESSIONAL,
  ENTRY_CONFIG_ENTERPRISE,
  getAnimationConfigForTier,
  getEntryConfigForTier,
  getLoopConfigForTier,
  getParticleConfigForTier,
} from './global';
