-- Migration 083: Alert Animations
-- Stores animated alert configurations and exports
-- Created: January 5, 2026
-- Access: Pro and Studio subscription tiers only

-- ============================================================================
-- Alert Animation Projects Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS alert_animation_projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- Source asset reference
    source_asset_id UUID REFERENCES assets(id) ON DELETE SET NULL,
    source_url TEXT NOT NULL,
    
    -- Depth map (generated by Depth Anything V2)
    depth_map_url TEXT,
    depth_map_storage_path TEXT,
    depth_map_generated_at TIMESTAMPTZ,
    
    -- Animation configuration (JSONB for flexibility)
    animation_config JSONB NOT NULL DEFAULT '{
        "entry": null,
        "loop": null,
        "depth_effect": null,
        "particles": null,
        "duration_ms": 3000,
        "loop_count": 1
    }'::jsonb,
    
    -- Export settings
    export_format TEXT DEFAULT 'webm' CHECK (export_format IN ('webm', 'gif', 'apng')),
    export_width INTEGER DEFAULT 512,
    export_height INTEGER DEFAULT 512,
    export_fps INTEGER DEFAULT 30,
    
    -- Metadata
    name TEXT NOT NULL DEFAULT 'Untitled Animation',
    thumbnail_url TEXT,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Animation Presets Table (System + User Custom)
-- ============================================================================

CREATE TABLE IF NOT EXISTS animation_presets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Ownership (NULL = system preset)
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    
    -- Preset metadata
    name TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL CHECK (category IN ('entry', 'loop', 'depth', 'particles')),
    
    -- Animation definition
    config JSONB NOT NULL,
    
    -- Display
    preview_url TEXT,
    icon TEXT,
    sort_order INTEGER DEFAULT 0,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Alert Animation Exports Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS alert_animation_exports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES alert_animation_projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- Export details
    format TEXT NOT NULL CHECK (format IN ('webm', 'gif', 'apng', 'obs_url')),
    url TEXT NOT NULL,
    storage_path TEXT,
    file_size BIGINT,
    
    -- Export settings snapshot
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    fps INTEGER NOT NULL,
    duration_ms INTEGER NOT NULL,
    
    -- Animation config snapshot (for reproducibility)
    animation_config_snapshot JSONB,
    
    -- OBS Browser Source URL (for obs_url format)
    obs_browser_url TEXT,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Indexes
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_alert_animation_projects_user_id 
    ON alert_animation_projects(user_id);
CREATE INDEX IF NOT EXISTS idx_alert_animation_projects_source_asset 
    ON alert_animation_projects(source_asset_id);
CREATE INDEX IF NOT EXISTS idx_alert_animation_projects_updated 
    ON alert_animation_projects(updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_animation_presets_category 
    ON animation_presets(category);
CREATE INDEX IF NOT EXISTS idx_animation_presets_system 
    ON animation_presets(user_id) WHERE user_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_alert_animation_exports_project 
    ON alert_animation_exports(project_id);
CREATE INDEX IF NOT EXISTS idx_alert_animation_exports_user 
    ON alert_animation_exports(user_id);

-- ============================================================================
-- Row Level Security
-- ============================================================================

ALTER TABLE alert_animation_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE animation_presets ENABLE ROW LEVEL SECURITY;
ALTER TABLE alert_animation_exports ENABLE ROW LEVEL SECURITY;

-- Projects: Users see their own
CREATE POLICY alert_animation_projects_select_own ON alert_animation_projects
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY alert_animation_projects_insert_own ON alert_animation_projects
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY alert_animation_projects_update_own ON alert_animation_projects
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY alert_animation_projects_delete_own ON alert_animation_projects
    FOR DELETE USING (auth.uid() = user_id);

-- Presets: Users see system presets + their own
CREATE POLICY animation_presets_select ON animation_presets
    FOR SELECT USING (user_id IS NULL OR auth.uid() = user_id);
CREATE POLICY animation_presets_insert_own ON animation_presets
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY animation_presets_update_own ON animation_presets
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY animation_presets_delete_own ON animation_presets
    FOR DELETE USING (auth.uid() = user_id);

-- Exports: Users see their own
CREATE POLICY alert_animation_exports_select_own ON alert_animation_exports
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY alert_animation_exports_insert_own ON alert_animation_exports
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- Triggers
-- ============================================================================

CREATE OR REPLACE FUNCTION update_alert_animation_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER alert_animation_projects_updated_at
    BEFORE UPDATE ON alert_animation_projects
    FOR EACH ROW EXECUTE FUNCTION update_alert_animation_updated_at();

-- ============================================================================
-- Seed System Presets (All free for Pro users)
-- ============================================================================

INSERT INTO animation_presets (id, user_id, name, description, category, config, icon, sort_order) VALUES

-- Entry Animations
(gen_random_uuid(), NULL, 'Pop In', 'Scale from 0 with elastic bounce', 'entry', 
 '{"type": "pop_in", "duration_ms": 500, "easing": "elastic.out(1, 0.3)", "scale_from": 0, "bounce": 0.3}', 
 '🎯', 1),

(gen_random_uuid(), NULL, 'Slide In', 'Slide from any direction', 'entry',
 '{"type": "slide_in", "duration_ms": 400, "easing": "power2.out", "direction": "left", "distance_percent": 120}',
 '➡️', 2),

(gen_random_uuid(), NULL, 'Fade In', 'Smooth opacity with subtle scale', 'entry',
 '{"type": "fade_in", "duration_ms": 300, "easing": "power1.inOut", "scale_from": 0.9, "opacity_from": 0}',
 '✨', 3),

(gen_random_uuid(), NULL, 'Burst', 'Explosive entry from center', 'entry',
 '{"type": "burst", "duration_ms": 600, "easing": "back.out(1.7)", "scale_from": 2.5, "opacity_from": 0, "rotation_from": 15}',
 '💥', 4),

-- Loop Animations
(gen_random_uuid(), NULL, 'Float', 'Gentle hover/bob motion', 'loop',
 '{"type": "float", "amplitude_y": 8, "amplitude_x": 2, "frequency": 0.5, "phase_offset": 0}',
 '💫', 1),

(gen_random_uuid(), NULL, 'Pulse', 'Subtle breathing scale effect', 'loop',
 '{"type": "pulse", "scale_min": 0.97, "scale_max": 1.03, "frequency": 0.8, "easing": "sine.inOut"}',
 '💓', 2),

(gen_random_uuid(), NULL, 'Glow', 'Pulsing outer glow/bloom', 'loop',
 '{"type": "glow", "color": "#ffffff", "intensity_min": 0.2, "intensity_max": 0.8, "frequency": 0.6, "blur_radius": 20}',
 '🔆', 3),

(gen_random_uuid(), NULL, 'Wiggle', 'Playful rotation shake', 'loop',
 '{"type": "wiggle", "angle_max": 3, "frequency": 3, "decay": 0}',
 '🎪', 4),

-- 3D Depth Effects
(gen_random_uuid(), NULL, 'Parallax', 'Depth layers move at different speeds', 'depth',
 '{"type": "parallax", "intensity": 0.5, "trigger": "mouse", "invert": false, "smooth_factor": 0.1}',
 '🌀', 1),

(gen_random_uuid(), NULL, 'Tilt', '3D card rotation following mouse', 'depth',
 '{"type": "tilt", "max_angle_x": 15, "max_angle_y": 15, "perspective": 1000, "scale_on_hover": 1.05}',
 '💎', 2),

(gen_random_uuid(), NULL, 'Pop Out', 'Foreground elements pop toward viewer', 'depth',
 '{"type": "pop_out", "depth_scale": 40, "trigger": "on_enter", "duration_ms": 800, "easing": "power2.out"}',
 '🎭', 3),

-- Particle Effects
(gen_random_uuid(), NULL, 'Sparkles', 'Floating glitter particles', 'particles',
 '{"type": "sparkles", "count": 25, "color": "#ffd700", "color_variance": 0.2, "size_min": 2, "size_max": 6, "speed": 1, "lifetime_ms": 2000, "spawn_area": "around"}',
 '✨', 1),

(gen_random_uuid(), NULL, 'Confetti', 'Celebration burst effect', 'particles',
 '{"type": "confetti", "count": 60, "colors": ["#ff0000", "#00ff00", "#0000ff", "#ffff00", "#ff00ff", "#00ffff"], "size": 8, "gravity": 0.4, "spread": 180, "lifetime_ms": 3000}',
 '🎊', 2),

(gen_random_uuid(), NULL, 'Hearts', 'Floating heart particles', 'particles',
 '{"type": "hearts", "count": 18, "color": "#ff69b4", "color_variance": 0.3, "size_min": 6, "size_max": 14, "float_speed": 0.6, "sway_amount": 20, "lifetime_ms": 4000}',
 '💕', 3),

(gen_random_uuid(), NULL, 'Fire', 'Flame particle effect', 'particles',
 '{"type": "fire", "count": 40, "colors": ["#ff4500", "#ff6600", "#ff8c00", "#ffd700"], "size_min": 4, "size_max": 12, "speed": 1.5, "turbulence": 0.3, "lifetime_ms": 1500}',
 '🔥', 4)

ON CONFLICT DO NOTHING;
