-- ============================================================================
-- Diagnostic: Check Usage Tracking for dadbodgeoff@gmail.com
-- ============================================================================
-- Run this in Supabase SQL Editor to diagnose the usage tracking issue
-- ============================================================================

-- 1. Check current user data
SELECT 
    id,
    email,
    display_name,
    subscription_tier,
    subscription_status,
    assets_generated_this_month,
    created_at,
    updated_at
FROM users 
WHERE email = 'dadbodgeoff@gmail.com';

-- 2. Count actual assets generated by this user
SELECT 
    COUNT(*) as actual_asset_count,
    MIN(created_at) as first_asset,
    MAX(created_at) as last_asset
FROM assets 
WHERE user_id = (SELECT id FROM users WHERE email = 'dadbodgeoff@gmail.com');

-- 3. Count completed generation jobs
SELECT 
    COUNT(*) as completed_jobs,
    MIN(created_at) as first_job,
    MAX(created_at) as last_job
FROM generation_jobs 
WHERE user_id = (SELECT id FROM users WHERE email = 'dadbodgeoff@gmail.com')
AND status = 'completed';

-- 4. Check if increment_user_usage function exists
SELECT 
    routine_name,
    routine_type
FROM information_schema.routines 
WHERE routine_name = 'increment_user_usage';

-- 5. Test the increment function manually (CAREFUL - this will increment!)
-- Uncomment to test:
-- SELECT increment_user_usage((SELECT id FROM users WHERE email = 'dadbodgeoff@gmail.com'));

-- 6. Fix: Sync the counter to actual asset count
-- This will set assets_generated_this_month to the actual count of assets
-- Uncomment to run:
/*
UPDATE users 
SET assets_generated_this_month = (
    SELECT COUNT(*) 
    FROM assets 
    WHERE assets.user_id = users.id
)
WHERE email = 'dadbodgeoff@gmail.com';
*/
